import Head from 'next/head'
import { FC, ReactNode } from 'react'

type Props = {
  title: string
  children: ReactNode
}

export const LoginLayout: FC<Props> = ({
  children,
  title = 'PortfolioApp',
}) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='container mx-auto flex min-h-screen flex-col items-center justify-center p-4'>
        {children}
      </main>
    </>
  )
}
